# -*- coding: utf-8 -*-
"""Task-6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F1eEA4EMjaZxkhBhRkdl_44HuiN40Wwp
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model

from google.colab import drive
drive.mount('/content/drive')

"""# Brain vs. Body Weight
In the file brain_body.txt, the average brain and body weight for a number of mammal species are recorded. Load this data into a Pandas data frame

# Tasks

1.   Find the linear regression equation for this data for brain weight to body weight.
2.   Chart the original data and the equation on the chart.
3.   Find the equation's  R2  score (use the .score method) to determine whether the equation is a good fit for this data. (0.8 and greater is considered a strong correlation.)
"""

df = pd.read_fwf('/content/drive/MyDrive/Colab Notebooks/Task-6/brain-body.txt')
df.head()

x = df['Brain']
y = df['Body']
x = x.to_frame()
reg = linear_model.LinearRegression()
reg.fit(x, y)

plt.scatter(x, y, color='red')
plt.plot(x,reg.predict(x), color='blue')

print('r-squared: ', reg.score(x, y))